### ISSUE TITLE
Successfully committed the change to the ledger by the peer

### ISSUE THREAD

**Issue by robelkebede** [hyperledger/education#118]
![git](https://user-images.githubusercontent.com/16935562/49284681-2a587e80-f44a-11e8-9ffe-c60995935799.PNG)

![git2](https://user-images.githubusercontent.com/16935562/49284685-2f1d3280-f44a-11e8-80eb-a89da2536a4e.PNG)

Successfully committed the change to the ledger by the peer but it is not upadating the ledger what is the problem Thank you.

**Comment by robelkebede44** [comment]
@vishal3152  thank you for the answer but i am a new to fabric how to read the emitted block

**Comment by vishal3152** [comment]
This is one of the way :-
 
var startBlockListener = async function () {
     const client = await Client.loadFromConfig("<file path>");
     const channel = client.getChannel("<channelName>");
    var eh = channel.getChannelEventHubsForOrg()[0];// read from network-config.json
    var block_reg = eh.registerBlockEvent((block) => {
        console.log('Successfully received the block event: ' + block.number);
            // read block here
   }
startBlockListener().then(() => {});
