### ISSUE TITLE
Missing source material for course LFS170x

### ISSUE THREAD

**Issue by NeroVanbiervliet** [hyperledger/education#125]
This repo does not contain the source of LFS17**0**x titled "Blockchain: Understanding Its Uses and Implications". 
Is feedback accepted elsewhere or can I submit issues here as well for this course?

**Comment by tkuhrt** [comment]
Best to provide that feedback directly via the EdX platform.

**Comment by NeroVanbiervliet** [comment]
Thanks, I'll close this issue.
