### ISSUE TITLE
Can not Create Tuna Record. Tuna record creation time is forever.

### ISSUE THREAD

**Issue by truestep** [hyperledger/education#14]
Tuna record creation time is forever.
Tried with both
with sawtooth-default.yaml from master
and with 0.8 images from this PR https://github.com/hyperledger/education/pull/12

During the creation of the "Tuna Record" call to
http://localhost:8080/batch_status?id=3b7062802b579ace1e1e89bb1af6b37eaee521026f46a3ed1a17db70aec38307539e7bba5d525c1ef8bfd96dafef396eae4499a0d5d30b2956db9293b807b3e3&wait%22
returns:
```{
data: [
{
id: "3b7062802b579ace1e1e89bb1af6b37eaee521026f46a3ed1a17db70aec38307539e7bba5d525c1ef8bfd96dafef396eae4499a0d5d30b2956db9293b807b3e3",
invalid_transactions: [ ],
status: "PENDING"
}
],
link: "http://localhost:8080/batch_status?id=3b7062802b579ace1e1e89bb1af6b37eaee521026f46a3ed1a17db70aec38307539e7bba5d525c1ef8bfd96dafef396eae4499a0d5d30b2956db9293b807b3e3&wait""
}
```

part of the log from dockers:

> sawtooth-validator-default | [2017-12-30 22:17:47.925 DEBUG    selector_events] Using selector: ZMQSelector
sawtooth-validator-default | [2017-12-30 22:17:47.925 INFO     interconnect] Listening on tcp://eth0:8800
sawtooth-validator-default | [2017-12-30 22:17:47.925 DEBUG    dispatch] Added send_message function for connection ServerThread
sawtooth-validator-default | [2017-12-30 22:17:47.926 DEBUG    dispatch] Added send_last_message function for connection ServerThread
sawtooth-validator-default | [2017-12-30 22:17:47.927 INFO     chain] Chain controller initialized with chain head: 42cf152c(0, S:24d4c66e, P:00000000)
sawtooth-validator-default | [2017-12-30 22:17:47.927 INFO     publisher] Now building on top of block: 42cf152c(0, S:24d4c66e, P:00000000)
sawtooth-validator-default | [2017-12-30 22:17:47.929 DEBUG    publisher] Loaded batch injectors: []
sawtooth-client-default | creating key directory: /root/.sawtooth/keys
sawtooth-client-default | writing file: /root/.sawtooth/keys/root.priv
sawtooth-client-default | writing file: /root/.sawtooth/keys/root.pub
sawtooth-validator-default | [2017-12-30 22:17:54.502 DEBUG    interconnect] ServerThread receiving CLIENT_STATE_LIST_REQUEST message: 81 bytes
sawtooth-validator-default | [2017-12-30 22:17:54.502 DEBUG    interconnect] ServerThread sending CLIENT_STATE_LIST_RESPONSE to b'bffc3624c2ef4caf'
sawtooth-validator-default | [2017-12-30 22:18:02.420 DEBUG    interconnect] ServerThread receiving CLIENT_BATCH_SUBMIT_REQUEST message: 924 bytes
sawtooth-validator-default | [2017-12-30 22:18:02.422 DEBUG    executor] no transaction processors registered for processor type transfer-chain: 0.0: application/json
sawtooth-validator-default | [2017-12-30 22:18:02.423 INFO     executor] Waiting for transaction processor (transfer-chain, 0.0, application/json)

**Comment by truestep** [comment]
just forgot to run the processor

**Comment by glendjustus** [comment]
I can't get Create Tuna Record to work. I started the processor with the following text as the last message in the terminal: "Initializing JSON handler for Sawtooth Tuna Chain." Does that mean the processor is running? Any ideas what I can do to make this work?
