### ISSUE TITLE
outdated link to Hyperledger Indy Project

### ISSUE THREAD

**Issue by p-alik** [hyperledger/education#149]
[Hyperledger Indy Agent Demonstration](https://github.com/hyperledger/education/blob/master/LFS171x/indy-material/nodejs/README.md)

The link in the sentence

> To learn more about Hyperledger Indy, see the project wiki - https://wiki.hyperledger.org/projects/indy.

should be replaced by https://wiki.hyperledger.org/display/indy

**Comment by tkuhrt** [comment]
Agree, @p-alik. Did you want to do a PR for this?
