### ISSUE TITLE
sawtooth-default.yaml does not load up with docker-compose

### ISSUE THREAD

**Issue by coolsvap** [hyperledger/education#22]
When running the following command 

# docker-compose -f sawtooth-default.yaml up

it gives following error,

ERROR: Version in "./sawtooth-default.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by tkuhrt** [comment]
This error is caused by the version of Docker and Docker Compose that you have installed. From the course material "Check to make sure that you have Docker version 17.03.1-ce or greater, and Docker Compose version 1.9.0 or greater".

**Comment by sedacrivity** [comment]
Hi,

Actually had exactly same issue with the sawtooth default yaml file ... version "2.1" in the file gives the above mentioned error .. when changing it to version '2.0' it works ...

I do have more recent versions:

docker
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:38 2018
 OS/Arch:      linux/amd64

docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.14

Running on Ubuntu 17.10

**Comment by DJWG** [comment]
Hi, how do you update the composer from 1.8 to 1.9 ? I tried to follow the instructions on https://github.com/docker/compose/releases but I couldn't update it. Can anybody please give me detailed step by step "how to", sorry but I am totally new to this. cheers!

**Comment by tkuhrt** [comment]
Hi, DJWG.

Can you provide a bit more detail? What operating system are you using?
What exact steps did you follow?

**Comment by DJWG** [comment]
Hi,

I am using ubuntu 64 on a virtual machine, just like in the installation guide for windows. 

I followed the link provided in the chapter "installing docker" https://docs.docker.com/install/linux/docker-ce/ubuntu/

I went through all steps and then installed the composer as discribed in the next section:

$ sudo apt update

$ sudo apt install docker-compose

but my version is then docker version 18.03.1 and compose version 1.8.0
