### ISSUE TITLE
Migrate "Introduction to Hyperledger" from EdX to Markdown 

### ISSUE THREAD

**Issue by tkuhrt** [hyperledger/education#45]
As part of our effort to create a second revision of the LFS171x EdX course, migrate the chapter "Introduction to Hyperledger" to a markdown file located at `./LFS171x/docs/introduction-to-hyperledger.md` in the `import-edx-content` branch.

**Comment by nathalie-ckc** [comment]
I would like to sign up for this issue.  I don't have permissions to assign it to myself.
-Nathalie

**Comment by tkuhrt** [comment]
Hi, @nathalie-ckc. This particular issue has already been merged, and it should have been closed. I will do that now. We would love to have you sign up for another issue https://github.com/hyperledger/education/labels/edx-migration.  Let me make sure that you are part of the organization so that you can assign an issue to yourself.

**Comment by tkuhrt** [comment]
Wasn't really completed. Sorry for the confusion. Re-opened.

**Comment by nathalie-ckc** [comment]
Submitted Pull Request #62 last week to address this issue.

**Comment by nathalie-ckc** [comment]
Please use Pull Request #70 instead of #62.

**Comment by nathalie-ckc** [comment]
Review feedback addressed and pushed to branch used in pull request #70. Thanks, Tracy!

**Comment by nathalie-ckc** [comment]
Should be addressed by PR #70 . Please close this issue.
