### ISSUE TITLE
Migrate "Introduction to Hyperledger Iroha" from EdX to Markdown

### ISSUE THREAD

**Issue by tkuhrt** [hyperledger/education#48]
As part of our effort to create a second revision of the LFS171x EdX course, migrate the chapter "Introduction to Hyperledger Iroha" to a markdown file located at `./LFS171x/docs/introduction-to-hyperledger-iroha.md` in the `import-edx-content` branch.

**Comment by nathalie-ckc** [comment]
Created Pull Request #71 to address this issue.

**Comment by nathalie-ckc** [comment]
Review feedback addressed and pushed to branch used in pull request #71.  Thanks for reviewing, Tracy!

**Comment by nathalie-ckc** [comment]
Should be resolved by PR #71 .  Please close this issue.
