### ISSUE TITLE
Migrate "Glossary" from EdX to Markdown

### ISSUE THREAD

**Issue by tkuhrt** [hyperledger/education#52]
As part of our effort to create a second revision of the LFS171x EdX course, migrate the chapter "Glossary" to a markdown file located at `./LFS171x/docs/glossary.md` in the `import-edx-content` branch.

**Comment by nathalie-ckc** [comment]
Hi Tracy,
I would like to sign up for this issue. I think I am a member of the Hyperledger Github organization, but I am still not able to assign myself the issue.  I am going by these instructions, but with my permission level I don't have the tick-box mentioned: https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/

Please could you assign it to me?

Thanks,
Nathalie
