### ISSUE TITLE
Trouble to install it on mac using docker

### ISSUE THREAD

**Issue by ansonyao** [hyperledger/education#63]
I am following the tutorial to install it on mac. When I run the command 

`docker-compose -f sawtooth-default.yaml up`

It does download the images and runs but then it stops after printing the following lines:
sawtooth-shell-default | creating key directory: /root/.sawtooth/keys
sawtooth-shell-default | writing file: /root/.sawtooth/keys/root.priv
sawtooth-shell-default | writing file: /root/.sawtooth/keys/root.pub

Anyone can point me a direction on how to get it running on my mac?

**Comment by thaddeus-cambron** [comment]
I can look at it tomorrow morning if no one else is available to help you
trouble shoot. I will reinstall tomorrow morning.

Thaddeus

**Comment by ansonyao** [comment]
I followed the steps after the installation on tutorials and they are working. Seems it is just the console stopped printing after ```
sawtooth-shell-default | creating key directory: /root/.sawtooth/keys
sawtooth-shell-default | writing file: /root/.sawtooth/keys/root.priv
sawtooth-shell-default | writing file: /root/.sawtooth/keys/root.pub
```

**Comment by thaddeus-cambron** [comment]
👍

**Comment by TheRealDrBob** [comment]
I've also run into the same issue ([here](https://github.com/hyperledger/education/issues/58)) with the key generation, though, I have gotten a little past it by installing lower versions of docker and docker-compose. Currently, I'm usin Docker 17.03.1 and Docker-compose 1.9.0. 

Maybe you could try something similar and see if your luck is better than mine.
