### ISSUE TITLE
Wrong compose version

### ISSUE THREAD

**Issue by Rapso** [hyperledger/education#9]
LFS171 says you need at least 1.8.1 docker compose version but sawtooth-default.yaml  uses 2.1 version

**Comment by umtyzc** [comment]
Hi , I could not start the download without changing the sawtooth-default.yaml file version "2.1" to "2.0".

**Comment by tkuhrt** [comment]
@Rapso : The version specified in the sawtooth-default.yaml version specifies the compose file version, not the version of docker-compose that is required. See: https://docs.docker.com/compose/compose-file/compose-versioning/. In this document, you will see the following statement: "In addition to Compose file format versions shown in the table, the Compose itself is on a release schedule, as shown in Compose releases, but file format versions do not necessairly increment with each release. For example, Compose file format 3.0 was first introduced in Compose release 1.10.0, and versioned gradually in subsequent releases."

However, I also see this: "An upgrade of version 2 that introduces new parameters only available with Docker Engine version 1.12.0+. Version 2.1 files are supported by Compose 1.9.0+." Looks like we need to update the course to say that docker-compose version required is 1.9.0+. I will work on getting this updated today.

**Comment by tkuhrt** [comment]
Updated in the course to specify that 1.9.0 or greater is required for docker-compose. Thanks for your report!
